name: Validate Branch
description: Enforces uniform branch naming conventions


# ------------------------------------------------------------------------------


inputs:
  branch:
    description: Specified branch name to validate (optional, for testing)
    required: false


# ------------------------------------------------------------------------------


runs:
  using: node20
  main: "src/action.js"


# ------------------------------------------------------------------------------
