name: Validate Branch
author: github.com/mattpieterse
description: Enforces uniform branch naming conventions
branding:
  icon: branch
  color: blue

# ------------------------------------------------------------------------------


inputs:
  branch:
    description: Specified branch name to validate (optional, for testing)
    required: false


# ------------------------------------------------------------------------------


runs:
  using: node20
  main: "src/action.js"


# ------------------------------------------------------------------------------
